### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by ijackwu** [KeyneZzz/gitlab2dingsvr#1]
```
Traceback (most recent call last):
  File "labFetchUser.py", line 25, in <module>
    data_departments_list = data_departments["department"]
KeyError: 'department'
[12/Feb/2019 23:14:38]labFetchUser success
Traceback (most recent call last):
  File "gitlab2dingsvr.py", line 51, in <module>
    git_members = read_list_from_db("git_members")
  File "gitlab2dingsvr.py", line 28, in read_list_from_db
    user_list_tuple = sqc.execute("SELECT GITEMAIL,DINGUID FROM USERS")
sqlite3.OperationalError: no such table: USERS

```

启动不来

**Comment by KeyneZzz** [comment]
你需要新建一个sqlite数据库（推荐用 SQLiteStudio），文件名设为gitlab2ding.db，然后在里面建一张表，表的名字是USERS，字段配置如图，建好以后放到同个目录下面就好
![image](https://user-images.githubusercontent.com/6895745/52922595-3115d400-335d-11e9-96b9-30844450e514.png)
